name: Update S-AIS tenders weekly

on:
  schedule:
    - cron: '0 10 * * 1'  # Chaque lundi à 10h UTC = 7h du matin à Brasilia
  workflow_dispatch:       # Permet de le lancer manuellement si besoin

jobs:
  update-tenders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run tender collection script
        run: python scripts/collect_tenders.py

      - name: Commit and push changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add sais_tenders_2025.json || true
          git diff --quiet && echo "No changes to commit" || (git commit -m "Update tenders list $(date --utc +'%Y-%m-%d')" && git push)
